checks:
  argument-count:
    enabled: false
  method-complexity:
    enabled: false

plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-24
    checks:
      Rubocop/Metrics/MethodLength:
        enabled: false

  reek:
    enabled: true
