detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#to_camel_case
      - SmtpMock::ContextGeneratorHelper

  NestedIterators:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#define_attribute
      - SmtpMock::Cli::Resolver#resolve

  TooManyStatements:
    exclude:
      - SmtpMock::Cli::Resolver#resolve
      - SmtpMock::Server#run
