detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#to_camel_case
      - SmtpMock::ServerHelper#compose_command

  NestedIterators:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#define_attribute
      - SmtpMock::Cli::Resolver#resolve

  TooManyStatements:
    exclude:
      - SmtpMock::Cli::Resolver#resolve
      - SmtpMock::Server#run

  ControlParameter:
    exclude:
      - SmtpMock::ServerHelper#lsof_port_by_pid_result