detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#to_camel_case

  NestedIterators:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#define_attribute

  TooManyConstants:
    exclude:
      - SmtpMock
