---

detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#to_camel_case
      - SmtpMock::Cli::Resolver#install_to
      - SmtpMock::ServerHelper
      - SmtpMock::TestFramework::RSpec::Helper#smtp_mock_server
      - SmtpMock::RspecHelper::ContextGenerator#random_message
      - SmtpMock::RspecHelper::Dependency#compose_command
      - SmtpMock::RspecHelper::Server#create_fake_servers
      - SmtpMock::RspecHelper::Server#reset_err_log

  NestedIterators:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#define_attribute

  TooManyStatements:
    exclude:
      - SmtpMock::Server#run
      - SmtpMock::Cli::Resolver#install
      - SmtpMock::Cli::Resolver#resolve
      - SmtpMock::RspecHelper::Server#create_fake_servers

  TooManyInstanceVariables:
    exclude:
      - SmtpMock::Server

  LongParameterList:
    exclude:
      - SmtpMock::RspecHelper::Client#smtp_request
