---

detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#to_camel_case
      - SmtpMock::DependencyHelper#compose_command
      - SmtpMock::ServerHelper
      - SmtpMock::TestFramework::RSpec::Helper#smtp_mock_server
      - SmtpMock::ContextGeneratorHelper#random_message
      - SmtpMock::Cli::Resolver#install_to

  NestedIterators:
    exclude:
      - SmtpMock::CommandLineArgsBuilder#define_attribute

  TooManyStatements:
    exclude:
      - SmtpMock::Server#run
      - SmtpMock::ServerHelper#create_fake_servers
      - SmtpMock::Cli::Resolver#install
      - SmtpMock::Cli::Resolver#resolve

  TooManyInstanceVariables:
    exclude:
      - SmtpMock::Server

  LongParameterList:
    exclude:
      - SmtpMock::ClientHelper#smtp_request
